/*Frage 2: Welche Städte haben ein höheres Kriminalitätsaufkommen als der U.S. Amerikanische Durchschnitt?*/
SELECT LOCATION.CITY,LOCATION.POPULATION, FBI.Property_CRIME,
ROUND((FBI.Property_CRIME / LOCATION.POPULATION),4) AS relation
FROM LOCATION
INNER JOIN FBI ON LOCATION.ID = FBI.LOCATION_ID
WHERE (FBI.Property_CRIME / LOCATION.POPULATION) >
(SELECT
SUM(FBI.Property_CRIME) / 
SUM(LOCATION.POPULATION)
FROM FBI,LOCATION)
ORDER BY (FBI.Property_CRIME / LOCATION.POPULATION) DESC;

/*Frage 3: Welche Städte haben ein höheres Gewaltaufkommen im Verhältnis zur Bevölkerungszahl als der U.S. Amerikanische Durchschnitt?*/
SELECT LOCATION.CITY,LOCATION.POPULATION, FBI.VIOLANCE_CRIME,
ROUND((FBI.VIOLANCE_CRIME / LOCATION.POPULATION),4) AS relation
FROM LOCATION
INNER JOIN FBI ON LOCATION.ID = FBI.LOCATION_ID
WHERE (FBI.VIOLANCE_CRIME / LOCATION.POPULATION) >
(SELECT
SUM(FBI.VIOLANCE_CRIME) / 
SUM(LOCATION.POPULATION)
FROM FBI,LOCATION)
ORDER BY (FBI.VIOLANCE_CRIME / LOCATION.POPULATION) DESC;