DROP TABLE LOCATION;
DROP TABLE KEYWORDS;
DROP TABLE FBI;
DROP TABLE MATCH_QUERY_LOCATION;
DROP TABLE MATCH_QUERY_KEYWORDS;
DROP TABLE MATCH_QUERY_WEBSITE;

CREATE TABLE LOCATION(
	ID      	INTEGER NOT NULL ,
	CITY    	VARCHAR2(50) ,
	POPULATION  INTEGER,
	PRIMARY KEY(ID)
);
INSERT INTO LOCATION(CITY,ID,POPULATION)
SELECT DISTINCT(AOLDATA.LOCATION.CITY), MIN(AOLDATA.LOCATION.ZIP), MAX(AOLDATA.LOCATION.POPULATION) /*Popualtion muzss später aus der FBI Datenbank geholt werden*/
FROM AOLDATA.LOCATION
GROUP BY AOLDATA.LOCATION.CITY
ORDER BY CITY;


CREATE TABLE KEYWORDS(
	ID      	INTEGER NOT NULL ,
	VALUE   	VARCHAR2(50) ,
	CATEGORY  INTEGER,
	PRIMARY KEY(ID)
);
INSERT INTO KEYWORDS VALUES (1, 'weapon',1 );
INSERT INTO KEYWORDS VALUES (2, 'axe' ,1 );
INSERT INTO KEYWORDS VALUES (3, 'judo' ,1 );
INSERT INTO KEYWORDS VALUES(4, 'martial arts',1  );
INSERT INTO KEYWORDS VALUES(5, 'alarm' ,1 );
INSERT INTO KEYWORDS VALUES(6, 'pepper spray',1);

CREATE TABLE FBI(
	LOCATION_ID     	INTEGER NOT NULL ,
	PROPERTY_CRIME  INTEGER ,
	VIOLANCE_CRIME  INTEGER,
	PRIMARY KEY(LOCATION_ID),
	FOREIGN KEY(LOCATION_ID) REFERENCES LOCATION(ID)
);

CREATE TABLE MATCH_QUERY_LOCATION(
	USER_ID     	INTEGER NOT NULL ,
	LOCATION_ID  INTEGER,
	PRIMARY KEY(USER_ID),
	FOREIGN KEY(LOCATION_ID) REFERENCES  LOCATION(ID)
);

CREATE TABLE MATCH_QUERY_KEYWORDS(
	USER_ID     	INTEGER NOT NULL ,
	KEYWORD_ID  INTEGER,
	PRIMARY KEY(USER_ID,KEYWORD_ID),
	FOREIGN KEY(KEYWORD_ID) REFERENCES  KEYWORDS(ID)
);

CREATE TABLE MATCH_QUERY_WEBSITE(
	USER_ID     	INTEGER NOT NULL ,
	WEB_ID  INTEGER,
	PRIMARY KEY(USER_ID,WEB_ID)
);