SELECT AOLDATA.QUERYDATA.* FROM AOLDATA.QUERYDATA WHERE AOLDATA.QUERYDATA.ANONID = 2722 AND AOLDATA.QUERYDATA.QUERY LIKE '%colum%';
SELECT LOC.* FROM LOC WHERE LOC.CITY LIKE '%Columbus%';


DROP VIEW LOC;

CREATE VIEW LOC AS
SELECT DISTINCT(AOLDATA.LOCATION.CITY), AOLDATA.LOCATION.ZIP FROM AOLDATA.LOCATION ORDER BY CITY;

DROP VIEW match;

CREATE VIEW match AS 
SELECT 
AOLDATA.QUERYDATA.ANONID, 
AOLDATA.QUERYDATA.QUERY, 
LOC.ZIP, 
LOC.CITY
FROM AOLDATA.QUERYDATA 
INNER JOIN LOC ON AOLDATA.QUERYDATA.QUERY LIKE ('%' || LOWER(LOC.CITY) || '%')
WHERE AOLDATA.QUERYDATA.QUERYTIME >= TO_TIMESTAMP('2006-05-01','yyyy-mm-dd') 
AND AOLDATA.QUERYDATA.QUERYTIME < TO_TIMESTAMP('2006-05-02','yyyy-mm-dd')
AND  ROWNUM <= 10 ;