DROP VIEW match;
CREATE VIEW match AS 
SELECT AOLDATA.QUERYDATA.QUERY AS QUERY,(SELECT AOLDATA.LOCATION.CITY FROM AOLDATA.LOCATION GROUP BY AOLDATA.LOCATION.CITY) AS CITY, AOLDATA.QUERYDATA.ANONID AS USER_ID 
FROM AOLDATA.QUERYDATA 
INNER JOIN AOLDATA.LOCATION ON AOLDATA.QUERYDATA.QUERY LIKE ('%' || LOWER(CITY) || '%')
WHERE AOLDATA.QUERYDATA.QUERYTIME >= TO_TIMESTAMP('2006-05-01','yyyy-mm-dd') 
AND AOLDATA.QUERYDATA.QUERYTIME < TO_TIMESTAMP('2006-05-02','yyyy-mm-dd');