CREATE OR REPLACE VIEW LOCATIONVIEW AS
SELECT DISTINCT(AOLDATA.LOCATION.CITY) AS CITY, MIN(AOLDATA.LOCATION.ZIP) AS LOCATION_ID
FROM AOLDATA.LOCATION group by (AOLDATA.LOCATION.CITY)
ORDER BY CITY;

CREATE OR REPLACE VIEW LOCATIONMATCHVIEW AS
SELECT AOLDATA.QUERYDATA_IDX.ANONID,
LOCATIONVIEW.LOCATION_ID FROM AOLDATA.QUERYDATA_IDX,
LOCATIONVIEW WHERE CONTAINS(AOLDATA.QUERYDATA_IDX.QUERY, LOWER(LOCATIONVIEW.CITY), 1) > 0
  /*AND ROWNUM <= 10000 */
GROUP BY AOLDATA.QUERYDATA_IDX.ANONID, LOCATIONVIEW.LOCATION_ID
ORDER BY AOLDATA.QUERYDATA_IDX.ANONID;

SELECT LOCATIONMATCHVIEW.CITY, Count(LOCATIONMATCHVIEW.CITY)
FROM LOCATIONMATCHVIEW, AOLDATA.QUERYDATA_IDX LEFT JOIN
(SELECT ACTIVE_DEFENSE.KEYWORD
FROM ACTIVE_DEFENSE
UNION
SELECT PASSIVE_DEFENSE.KEYWORDS
FROM PASSIVE_DEFENSE) Keywords
ON CONTAINS  (AOLDATA.QUERYDATA_IDX.Query, KEYWORDS.KEYWORD,1)>0
WHERE AOLDATA.QUERYDATA_IDX.ANONID = LOCATIONMATCHVIEW.ANONID
AND ROWNUM <= 10
GROUP BY LOCATIONMATCHVIEW.CITY;


